name: Build Companion Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Generate artifact name
        id: name
        run: |
          VERSION=$(grep '^version=' companion/module/module.prop | cut -d= -f2 | tr -d 'v')
          echo "artifact_name=dusk-companion-v${VERSION}_run_${{ github.run_number }}_$(TZ=UTC date +%d.%m.%y)" >> "$GITHUB_OUTPUT"
      - name: Upload Companion Module
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.name.outputs.artifact_name }}
          path: companion/module/
          if-no-files-found: error
